[workspace]
[package]
name = "glutton-update-bin"
version = "1.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
description = "Script to update Glutton parachains storage values"


[[bin]]
name = "glutton-update"
path = "src/main.rs"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.4.0", default-features = false }
subxt = { path = "../../../../subxt/subxt", default-features = true }
# subxt = "0.29.0"
sp-keyring = "23.0.0"
tokio = { version = "1.28", features = ["macros", "time", "rt-multi-thread"] }
hex = "0.4.3"
# sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "master" }
sp-core = {path = "/Users/nacho/Desktop/PARITY/Repos/substrate/primitives/core" }
# glutton-runtime = { path = "../../../parachains/runtimes/glutton/glutton-kusama" }
# pallet-glutton = { default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
